name: Tests Templates

on: [push]

jobs:
  templates-test-macos:
    name: Tests Mac OS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ritchie CLI
        run: |
          curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
          rit --version
          echo '{"addCommons":true, "sendMetrics":true, "runType":"local"}' | rit init --stdin > /dev/null
          rit

      - name: Create formulas
        run: |
          mkdir -p $HOME/workspace-template-test
          cp $HOME/.rit/repos/commons/templates/create_formula/languages/* $HOME/workspace-template-test/
          rit add workspace --name="templates-test" --path="$HOME/workspace-template-test/"
          rit

  templates-test-ubuntu:
    name: Tests Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ritchie CLI
        run: |
          curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
          rit --version
          echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin > /dev/null
          rit

  templates-test-windows:
    name: Tests Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ritchie CLI
        run: echo %PATH%